name: Daily script run and push

on:
  schedule:
    # runs at 15, 16, 17 UTC (= 17h, 18h, 19h Brussels time in CEST)
    - cron: '0 15,16,17 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  START_DATE: '2025-08-27'
  DAYS: '18'
  TARGET_FOLDER: 'data/processed'
  R_SCRIPT: 'scripts/process_results.R'

jobs:
  run-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check date range (stop if outside 2-week window)
        id: daterange
        run: |
          START=${{ env.START_DATE }}
          DAYS=${{ env.DAYS }}
          END=$(date -d "$START + $((DAYS - 1)) days" +%Y-%m-%d)
          NOW=$(date -u +%Y-%m-%d)
          echo "Now (UTC): $NOW"
          echo "Start: $START  End: $END"
          if [[ "$NOW" < "$START" || "$NOW" > "$END" ]]; then
            echo "Outside date range - exiting without running."
            exit 0
          fi
          echo "In date range - continue."

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxml2-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      - name: Install pak
        run: Rscript -e 'install.packages("pak", repos="https://r-lib.github.io/p/pak/dev/")'

      - name: Install R dependencies
        run: |
          Rscript -e 'pak::pak(c(
            "dplyr",
            "tidyr",
            "glue",
            "readr",
            "rvest",
            "furrr",
            "purrr",
            "DBI",
            "RPostgres",
            "lubridate",
            "stringr"
          ))'

      - name: Run your R script
        run: Rscript ${{ env.R_SCRIPT }}

      - name: Show git status (debug)
        run: |
          git status --porcelain
          git add -A
          git status --porcelain

      - name: Commit & push generated folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add ${{ env.TARGET_FOLDER }} || true

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update: write ${{ env.TARGET_FOLDER }} (run $GITHUB_RUN_ID)"
            git push
          fi
